import 'package:flutter/material.dart';



class MemberPage extends StatefulWidget {
  const MemberPage({Key? key}) : super(key: key);

  @override
  State<MemberPage> createState() => _MemberPageState();
}

class _MemberPageState extends State<MemberPage> {
  @override
  Widget build(BuildContext context) {
    return ListView(
        children: const [
          ListTile(
            leading: Icon(Icons.adb_sharp),
            title: Text('아빠',
              style: TextStyle(
                  fontSize: 20
              ),
            ),
            subtitle: Text('화장실 청소 해놨다',
            ),
            trailing: Text('2위'),
          ),
          ListTile(
            leading: Icon(Icons.adb_sharp),
            title: Text('엄마',
              style: TextStyle(
                  fontSize: 20
              ),
            ),
            subtitle: Text('공주님 왕자님~ 방 청소 좀 하세요^^',
            ),
            trailing: Text('1위'),
          ),
          ListTile(
            leading: Icon(Icons.adb_sharp),
            title: Text('딸',
              style: TextStyle(
                  fontSize: 20
              ),),
            subtitle: Text('시험공부중! 청소는 나중에',
            ),
            trailing: Text('3위'),
          ),ListTile(
            leading: Icon(Icons.adb_sharp),
            title: Text('아들',
              style: TextStyle(
                  fontSize: 20
              ),),
            subtitle: Text('집에 안들어가요',
            ),
            trailing: Text('4위'),
          ),


        ],

    );
  }
}
class SecondPage extends StatefulWidget {
  const SecondPage({Key? key}) : super(key: key);

  @override
  State<SecondPage> createState() => _SecondPageState();
}

class _SecondPageState extends State<SecondPage> {
  @override
  Widget build(BuildContext context) {
    return Container(
      child: Text('Second'),
    );
  }
}
class ThirdPage extends StatefulWidget {
  const ThirdPage({Key? key}) : super(key: key);

  @override
  State<ThirdPage> createState() => _ThirdPageState();
}

class _ThirdPageState extends State<ThirdPage> {
  @override
  Widget build(BuildContext context) {
    return Container(
      child: Text('Third'),
    );
  }
}
class Autogenerated {
  int? id;
  int? room;
  Author? author;
  String? createDate;
  String? modifyDate;
  int? event;
  String? image;
  String? text;

  Autogenerated(
      {this.id,
        this.room,
        this.author,
        this.createDate,
        this.modifyDate,
        this.event,
        this.image,
        this.text});

  Autogenerated.fromJson(Map<String, dynamic> json) {
    id = json['id'];
    room = json['room'];
    author =
    json['author'] != null ? new Author.fromJson(json['author']) : null;
    createDate = json['create_date'];
    modifyDate = json['modify_date'];
    event = json['event'];
    image = json['image'];
    text = json['text'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['id'] = this.id;
    data['room'] = this.room;
    if (this.author != null) {
      data['author'] = this.author!.toJson();
    }
    data['create_date'] = this.createDate;
    data['modify_date'] = this.modifyDate;
    data['event'] = this.event;
    data['image'] = this.image;
    data['text'] = this.text;
    return data;
  }
}

class Author {
  String? nickname;
  int? icon;
  String? stateMessage;
  User? user;

  Author({this.nickname, this.icon, this.stateMessage, this.user});

  Author.fromJson(Map<String, dynamic> json) {
    nickname = json['nickname'];
    icon = json['icon'];
    stateMessage = json['state_message'];
    user = json['user'] != null ? new User.fromJson(json['user']) : null;
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['nickname'] = this.nickname;
    data['icon'] = this.icon;
    data['state_message'] = this.stateMessage;
    if (this.user != null) {
      data['user'] = this.user!.toJson();
    }
    return data;
  }
}

class User {
  int? id;
  String? username;

  User({this.id, this.username});

  User.fromJson(Map<String, dynamic> json) {
    id = json['id'];
    username = json['username'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['id'] = this.id;
    data['username'] = this.username;
    return data;
  }
}

// class LastPage extends StatefulWidget {
//   const LastPage({Key? key}) : super(key: key);
//
//   @override
//   State<LastPage> createState() => _LastPageState();
// }
//
// class _LastPageState extends State<LastPage> {
//   @override
//   Widget build(BuildContext context) {
//     return Container(
//       child: Text('Last'),
//     );
//   }
// }
//


